CONTIKI_PROJECT = node sink
all: $(CONTIKI_PROJECT)

MAKE_MAC     = MAKE_MAC_TSCH
MAKE_ROUTING = MAKE_ROUTING_RPL_LITE
MODULES     += os/services/orchestra

CONTIKI = ../contiki-ng

include $(CONTIKI)/Makefile.include
