<?xml version="1.0" encoding="UTF-8"?>
<simconf>
  <simulation>
    <title>wsn-2sink-full</title>
    <randomseed>123456</randomseed>
    <motedelay_us>1000000</motedelay_us>
    <radiomedium>
      org.contikios.cooja.radiomediums.UDGM
      <transmitting_range>50.0</transmitting_range>
      <interference_range>50.0</interference_range>
      <success_ratio_tx>1.0</success_ratio_tx>
      <success_ratio_rx>1.0</success_ratio_rx>
    </radiomedium>
    <events>
      <logoutput>40000</logoutput>
    </events>
    <motetype>
      org.contikios.cooja.contikimote.ContikiMoteType
      <identifier>sinktype</identifier>
      <description>Sink</description>
      <source>[CONFIG_DIR]/nodes/sink.c</source>
      <commands>make sink.cooja TARGET=cooja -j12</commands>
      <moteinterface>org.contikios.cooja.interfaces.Position</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiMoteID</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiRS232</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiClock</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiRadio</moteinterface>
    </motetype>
    <motetype>
      org.contikios.cooja.contikimote.ContikiMoteType
      <identifier>nodetype</identifier>
      <description>Sensor node</description>
      <source>[CONFIG_DIR]/nodes/node.c</source>
      <commands>make node.cooja TARGET=cooja</commands>
      <moteinterface>org.contikios.cooja.interfaces.Position</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiMoteID</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiRS232</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiClock</moteinterface>
      <moteinterface>org.contikios.cooja.contikimote.interfaces.ContikiRadio</moteinterface>
    </motetype>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>50.0</x>
      <y>50.0</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>1</id>
    </interface_config>
    <motetype_identifier>sinktype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>128.98</x>
      <y>62.51</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>2</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>58.79</x>
      <y>101.7</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>3</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>11.86</x>
      <y>-26.88</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>4</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>130.71</x>
      <y>99.07</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>5</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>113.82</x>
      <y>62.09</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>6</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>3.27</x>
      <y>48.43</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>7</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>55.15</x>
      <y>65.46</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>8</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>-27.42</x>
      <y>27.54</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>9</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>10.24</x>
      <y>25.03</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>10</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>139.89</x>
      <y>53.67</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>11</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>21.26</x>
      <y>-35.04</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>12</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>82.64</x>
      <y>98.34</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>13</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>30.0</x>
      <y>90.0</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>14</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>75.0</x>
      <y>67.39</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>15</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>-23.19</x>
      <y>-5.84</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>16</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>38.59</x>
      <y>-39.11</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>17</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>122.19</x>
      <y>37.69</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>18</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>-8.27</x>
      <y>30.24</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>19</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>-16.97</x>
      <y>-11.72</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>20</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>-32.08</x>
      <y>6.64</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>21</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>130.48</x>
      <y>73.84</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>22</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>38.31</x>
      <y>96.28</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>23</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>53.05</x>
      <y>78.08</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>24</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>44.44</x>
      <y>81.29</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>25</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>20.0</x>
      <y>90.0</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>26</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>500.0</x>
      <y>50.0</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>27</id>
    </interface_config>
    <motetype_identifier>sinktype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>515.31</x>
      <y>108.88</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>28</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>547.63</x>
      <y>29.97</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>29</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>437.69</x>
      <y>-0.97</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>30</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>494.59</x>
      <y>8.99</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>31</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>470.63</x>
      <y>77.77</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>32</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>436.59</x>
      <y>-26.65</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>33</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>470.2</x>
      <y>-18.42</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>34</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>514.93</x>
      <y>-40.58</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>35</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>546.89</x>
      <y>59.59</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>36</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>493.75</x>
      <y>105.82</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>37</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>543.01</x>
      <y>33.87</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>38</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>463.0</x>
      <y>135.99</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>39</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>435.83</x>
      <y>99.37</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>40</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>407.55</x>
      <y>74.45</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>41</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>501.09</x>
      <y>101.45</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>42</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>494.01</x>
      <y>124.68</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>43</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>561.24</x>
      <y>4.22</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>44</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>512.11</x>
      <y>112.03</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>45</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>400.3</x>
      <y>44.03</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>46</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>528.84</x>
      <y>58.8</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>47</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>476.95</x>
      <y>26.23</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>48</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>421.44</x>
      <y>91.81</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>49</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>481.45</x>
      <y>67.07</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>50</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>401.86</x>
      <y>31.84</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>51</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  <mote>
    <interface_config>
      org.contikios.cooja.interfaces.Position
      <x>530.0</x>
      <y>30.0</y>
      <z>0.0</z>
    </interface_config>
    <interface_config>
      org.contikios.cooja.contikimote.interfaces.ContikiMoteID
      <id>52</id>
    </interface_config>
    <motetype_identifier>nodetype</motetype_identifier>
  </mote>
  </simulation>
  <plugin>
    org.contikios.cooja.plugins.ScriptRunner
    <plugin_config>
      <script>var FileWriter = Java.type("java.io.FileWriter");
var FileReader = Java.type("java.io.FileReader");
var BufferedReader = Java.type("java.io.BufferedReader");
var File = Java.type("java.io.File");

var fileIndex = 1;
var lineCount = 0;
var maxLines = 50000;
var logFile = new FileWriter("../../../data/logs/run_" + fileIndex + ".log", false);
var cmdFile = new File("../../../data/logs/attack.cmd");

TIMEOUT(3600000, logFile.close(); log.testOK(););

while (true) {
    YIELD();
    try {
        logFile.write(time + " ID:" + id + " " + msg + "\n");
        logFile.flush();
        lineCount++;
        
        if (lineCount &gt;= maxLines) {
            logFile.close();
            fileIndex++;
            lineCount = 0;
            logFile = new FileWriter("../../../data/logs/run_" + fileIndex + ".log", false);
        }
        
        // --- C&amp;C File Bridge Logic ---
        if (cmdFile.exists()) {
            var reader = new BufferedReader(new FileReader(cmdFile));
            var cmd = reader.readLine();
            reader.close();
            if (cmd != null &amp;&amp; cmd.length() &gt; 0) {
                // Determine target node (Sybil is 53)
                var m = sim.getMoteWithID(53);
                if (m != null) {
                    write(m, cmd);
                }
            }
            cmdFile.delete();
        }
        // -----------------------------
        
    } catch (e) {
        logFile.close();
        throw e;
    }
}
</script>
      <active>true</active>
    </plugin_config>
    <width>600</width>
    <z>2</z>
    <height>600</height>
    <location_x>1</location_x>
    <location_y>1</location_y>
  </plugin>
</simconf>
